hazelcast:
  network:
    join:
      multicast:
        enabled: true

spring:
  h2:
    console:
      enabled:  true
  datasource:
    url: jdbc:h2:mem:testdb
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8081

